# Enabling/Disabling search paths 
# Pass true to include certain tools, false to disable.

# Cache paths from bleachbit 
cachePaths true 
historyPaths true

# Software specific paths 
logrotatePaths false
journaldPaths false

# OS specific paths 
ecleanPaths false
ecleanKernelPaths false
