# Enabling/Disabling search paths 
# Pass true to include certain tools, false to disable.
cachePaths true
historyPaths true

# Software specific paths 
logrotatePaths true
journaldPaths false

# Gentoo specific paths 
ecleanPaths false
ecleanKernelPaths false
