# Enabling/Disabling search paths 
# Pass true to include certain tools, false to disable.

# Bleachbit paths
cachePaths true
historyPaths true

# Software specific paths 
logrotatePaths false
journaldPaths false

# Gentoo specific paths 
ecleanPaths false
ecleanKernelPaths false
